name: Deploy FunctionApp

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: 'Firepuma-EmailAndPush-MicroService'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'FunctionApp'
  DOTNET_VERSION: '6.0'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: |
          dotnet restore Firepuma.EmailAndPush.Abstractions
          dotnet restore Firepuma.EmailAndPush.Client
          dotnet restore Firepuma.EmailAndPush.FunctionApp
          dotnet restore Firepuma.EmailAndPush.Tests

      - name: Build FunctionApp
        run: dotnet build --configuration Release --no-restore --output ./output
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Test
        run: dotnet test --no-restore

      - name: 'Deploy FunctionApp'
        uses: Azure/functions-action@v1
        id: deploy_functionapp
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: 'Publish Abstractions nuget package'
        id: publish_nuget_abstractions
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Firepuma.EmailAndPush.Abstractions/Firepuma.EmailAndPush.Abstractions.csproj
          BUILD_CONFIGURATION: Release
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # INCLUDE_SYMBOLS: true

      - name: 'Publish Client nuget package'
        id: publish_nuget_client
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Firepuma.EmailAndPush.Client/Firepuma.EmailAndPush.Client.csproj
          BUILD_CONFIGURATION: Release
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # INCLUDE_SYMBOLS: true